create table "public"."leaderboard" (
    "id" bigint generated by default as identity not null,
    "username" text not null,
    "score" integer not null,
    "submitted_at" timestamp with time zone default now()
);


alter table "public"."leaderboard" enable row level security;

create table "public"."notes" (
    "id" uuid not null default gen_random_uuid(),
    "title" text,
    "content" text,
    "created_at" timestamp with time zone not null default now(),
    "public" boolean,
    "session_id" uuid,
    "slug" text,
    "category" text,
    "emoji" text
);


alter table "public"."notes" enable row level security;

CREATE UNIQUE INDEX leaderboard_pkey ON public.leaderboard USING btree (id);

CREATE UNIQUE INDEX leaderboard_username_key ON public.leaderboard USING btree (username);

CREATE UNIQUE INDEX notes_pkey ON public.notes USING btree (id);

CREATE INDEX session_id_index ON public.notes USING btree (session_id);

alter table "public"."leaderboard" add constraint "leaderboard_pkey" PRIMARY KEY using index "leaderboard_pkey";

alter table "public"."notes" add constraint "notes_pkey" PRIMARY KEY using index "notes_pkey";

alter table "public"."leaderboard" add constraint "leaderboard_username_key" UNIQUE using index "leaderboard_username_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.delete_note(uuid_arg uuid, session_arg uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    DELETE FROM public.notes
    WHERE id = uuid_arg AND session_id = session_arg;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.select_note(note_slug_arg text)
 RETURNS SETOF notes
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
    SELECT *
    FROM notes
    WHERE slug = note_slug_arg LIMIT 1;
$function$
;

CREATE OR REPLACE FUNCTION public.select_session_notes(session_id_arg uuid)
 RETURNS SETOF notes
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
    SELECT *
    FROM notes
    WHERE session_id = session_id_arg;
$function$
;

CREATE OR REPLACE FUNCTION public.submit_score(p_username text, p_score integer)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  existing_score int;
begin
  -- Check if user already has a score
  select score into existing_score
  from leaderboard
  where username = p_username;
  
  -- Only update if no existing score or new score is higher
  if existing_score is null or p_score > existing_score then
    insert into leaderboard (username, score, submitted_at)
    values (p_username, p_score, current_timestamp)
    on conflict (username)
    do update set
      score = excluded.score,
      submitted_at = excluded.submitted_at
    where leaderboard.score < excluded.score;
    
    return json_build_object('success', true);
  end if;
  
  return json_build_object('success', false, 'message', 'Existing score is higher');
end;
$function$
;

CREATE OR REPLACE FUNCTION public.update_note(uuid_arg uuid, session_arg uuid, title_arg text, emoji_arg text, content_arg text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    UPDATE public.notes
    SET title = title_arg, 
        emoji = emoji_arg, 
        content = content_arg
    WHERE id = uuid_arg AND session_id = session_arg;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_note_content(uuid_arg uuid, session_arg uuid, content_arg text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    UPDATE public.notes
    SET content = content_arg
    WHERE id = uuid_arg AND session_id = session_arg;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_note_emoji(uuid_arg uuid, session_arg uuid, emoji_arg text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    UPDATE public.notes
    SET emoji = emoji_arg
    WHERE id = uuid_arg AND session_id = session_arg;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_note_title(uuid_arg uuid, session_arg uuid, title_arg text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    UPDATE public.notes
    SET title = title_arg
    WHERE id = uuid_arg AND session_id = session_arg;
END;
$function$
;

grant delete on table "public"."leaderboard" to "anon";

grant insert on table "public"."leaderboard" to "anon";

grant references on table "public"."leaderboard" to "anon";

grant select on table "public"."leaderboard" to "anon";

grant trigger on table "public"."leaderboard" to "anon";

grant truncate on table "public"."leaderboard" to "anon";

grant update on table "public"."leaderboard" to "anon";

grant delete on table "public"."leaderboard" to "authenticated";

grant insert on table "public"."leaderboard" to "authenticated";

grant references on table "public"."leaderboard" to "authenticated";

grant select on table "public"."leaderboard" to "authenticated";

grant trigger on table "public"."leaderboard" to "authenticated";

grant truncate on table "public"."leaderboard" to "authenticated";

grant update on table "public"."leaderboard" to "authenticated";

grant delete on table "public"."leaderboard" to "service_role";

grant insert on table "public"."leaderboard" to "service_role";

grant references on table "public"."leaderboard" to "service_role";

grant select on table "public"."leaderboard" to "service_role";

grant trigger on table "public"."leaderboard" to "service_role";

grant truncate on table "public"."leaderboard" to "service_role";

grant update on table "public"."leaderboard" to "service_role";

grant delete on table "public"."notes" to "anon";

grant insert on table "public"."notes" to "anon";

grant references on table "public"."notes" to "anon";

grant select on table "public"."notes" to "anon";

grant trigger on table "public"."notes" to "anon";

grant truncate on table "public"."notes" to "anon";

grant update on table "public"."notes" to "anon";

grant delete on table "public"."notes" to "authenticated";

grant insert on table "public"."notes" to "authenticated";

grant references on table "public"."notes" to "authenticated";

grant select on table "public"."notes" to "authenticated";

grant trigger on table "public"."notes" to "authenticated";

grant truncate on table "public"."notes" to "authenticated";

grant update on table "public"."notes" to "authenticated";

grant delete on table "public"."notes" to "service_role";

grant insert on table "public"."notes" to "service_role";

grant references on table "public"."notes" to "service_role";

grant select on table "public"."notes" to "service_role";

grant trigger on table "public"."notes" to "service_role";

grant truncate on table "public"."notes" to "service_role";

grant update on table "public"."notes" to "service_role";

create policy "Anyone can insert scores"
on "public"."leaderboard"
as permissive
for insert
to public
with check (true);


create policy "Anyone can insert to leaderboard"
on "public"."leaderboard"
as permissive
for insert
to public
with check (true);


create policy "Anyone can update scores"
on "public"."leaderboard"
as permissive
for update
to public
using (true);


create policy "Anyone can view leaderboard"
on "public"."leaderboard"
as permissive
for select
to public
using (true);


create policy "Anyone can view the leaderboard"
on "public"."leaderboard"
as permissive
for select
to public
using (true);


create policy "allow_all_users_insert_private_notes"
on "public"."notes"
as permissive
for insert
to public
with check ((public = false));


create policy "allow_all_users_select_public_notes"
on "public"."notes"
as permissive
for select
to public
using ((public = true));



